### ISSUE TITLE
Update to 1.10?

### ISSUE THREAD

**Issue by TheModdersDen** [sk89q/PlayBlock#7]
Hello. I am currently in the process of porting this handy mod to 1.10 (because why not)... I've run into a problem, however, and have decided to turn the both the creator, and any other maintainers of this mod.

The problem is that I can't seem to get the NBT packets to be sent between the client and server. It does not crash (or have any errors in eclipse) but doesn't provide anything useful in the log either... My code can be found here: https://github.com/TheModdersDen/MediaMod. This can be encountered when you place a projector, and then go into it's GUI, and try to change the width, height, URI, or anything else...

I've been looking here for information on packets in 1.10, but can't seem to wrap my head around it: https://github.com/Choonster/TestMod3

The log and any other potentially useful info can be found here: http://pastebin.com/U4prWrav

Also, the full log for the client can be found here: http://pastebin.com/n8D155RH

**Comment by sk89q** [comment]
I believe I already updated the mod to 1.10 locally in a branch but I don't know if it was a complete update. We also use PlayBlock on our vanilla servers, or at least we did until we updated to MC 1.11 two weeks ago. It works slightly different but the networking is unchanged if I recall. 

I will be posting the official 1.10 version soon since we are in the process of updating our modded servers to 1.10.

1.11 too for our vanilla servers.

**Comment by TheModdersDen** [comment]
OK. Awesome! Guess I'll just sit back and wait! :)

**Comment by TheModdersDen** [comment]
I see that there you guys have created a new branch for 1.10. I downloaded the files and got the starting point of my code update to 1.10 (which I got working with no errors). Feel free to take my code from here: https://github.com/TheModdersDen/MediaMod and use it to update this awesome project. Everything works as far as I know, with the exception of NBT data handling. I also haven't tested it on multiplayer, but it should work...

Also, the downloaded code from your repository did not setup the eclipse project when I used the command "gradlew eclipse" or "gradlew setupDecompWorkspace eclipse." So, you might want to get that fixed...

**Comment by TheModdersDen** [comment]
@sk89q Any word on the 1.10 update for this mod? Also, I can't seem to get the mod to play a YouTube playlist. Any idea on how to fix this (in the code, or in the way that I should format the URL)? Or is this something that will need to be worked on, modified, or implemented to get that feature working? 

As for the playlist problem, I think that it may be a problem with the way that I format the YouTube playlist because the latest 64-bit version of VLC doesn't seem to like the links either. I wonder if the PlayBlock mod is hard-coded to loop videos, and that's what's preventing it from playing playlists. Is this the case?

Either way, looking forward to seeing a 1.10.2 update to this awesome mod! 😄

**Comment by sk89q** [comment]
Not bright. I currently have no plans to work on it.

I think the playlist support is incomplete and I don't remember how much progress there was.

**Comment by TheModdersDen** [comment]
Darn... Mind if I give it a shot, and attempt to modify your mod? 😆

**Comment by sk89q** [comment]
Feel free

**Comment by TheModdersDen** [comment]
Alright. I'll give it a shot later in the summer (once school gets out), and if I have the time. 

Also, does this mean that you are (or are thinking about) dropping support for this mod, or discontinuing it? 😞 Or are you going to continue to support this mod, but not update the code of the mod (for example,  port it to 1.11.2)?

**Comment by Tampa** [comment]
Sorry to dig this up, but one of the forks also has begun update work on this tagging the branch ready for 1.12. It also has not seen an update in months sadly. I'm actually surprised this mod has not seen bigger attention as is, hopefully said fork works for 1.12, because there are still plenty of people playing that version(seeing as 1.13 and up doesn't work most of the time).
